### PR TITLE
🐛 Add lodash dependency

### LINKED ISSUE #124: Error: 'TypeError: this.activateMode' / lodash / Underscore
### Expected Behavior

I've created a block with cgb and used it within a page. After that I've inserted the default block **Image**.

### Actual Behavior

Immediately after inserting the **Image** block, it comes up these error:
```
TypeError: this.activateMode is not a function
    at media-views.min.js?ver=5.0.2:1
    at arrayEach (blocks.build.js?ver=1:3683)
    at Function.forEach (blocks.build.js?ver=1:12511)
    at n._createModes (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.e.View (backbone.min.js?ver=1.2.3:1)
    at n.constructor (wp-backbone.min.js?ver=5.0.2:1)
    at n.constructor (media-views.min.js?ver=5.0.2:1)
```
### Steps to Reproduce

1. `node -v`: v9.11.1
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn): -
4. `npm ls cgb-scripts` (if you haven’t ejected): -- cgb-scripts@1.11.1
5. Operating system: Win10
6. Browser and version (if relevant): Latest Chrome

### Possible Solution

1. Execute within your plugin directory `npm i --save babel-plugin-lodash`
2. Go to `[your-plugin-directory]/node_modules/cgb-scripts/config`
3. Open file `webpack.config.dev.js`
4. Search for line(s) `presets: [ require.resolve( 'babel-preset-cgb' ) ],`
5. Insert new line: `plugins: [ 'lodash' ],`
6. Open file `webpack.config.prod.js`
6. Repeat steps 4 + 5

After that you can use image plugin again w/o errors.

### LINKED ISSUE #133: Error: 'TypeError: this.activateMode' / lodash / Underscore
### Expected Behavior

I've created a block with cgb and used it within a page. After that I've inserted the default block **Image**.

### Actual Behavior

Immediately after inserting the **Image** block, it comes up these error:
```
TypeError: this.activateMode is not a function
    at media-views.min.js?ver=5.0.2:1
    at arrayEach (blocks.build.js?ver=1:3683)
    at Function.forEach (blocks.build.js?ver=1:12511)
    at n._createModes (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.initialize (media-views.min.js?ver=5.0.2:1)
    at n.e.View (backbone.min.js?ver=1.2.3:1)
    at n.constructor (wp-backbone.min.js?ver=5.0.2:1)
    at n.constructor (media-views.min.js?ver=5.0.2:1)
```
### Steps to Reproduce

1. `node -v`: v9.11.1
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn): -
4. `npm ls cgb-scripts` (if you haven’t ejected): -- cgb-scripts@1.11.1
5. Operating system: Win10
6. Browser and version (if relevant): Latest Chrome

### Possible Solution

1. Execute within your plugin directory `npm i --save babel-plugin-lodash`
2. Go to `[your-plugin-directory]/node_modules/cgb-scripts/config`
3. Open file `webpack.config.dev.js`
4. Search for line(s) `presets: [ require.resolve( 'babel-preset-cgb' ) ],`
5. Insert new line: `plugins: [ 'lodash' ],`
6. Open file `webpack.config.prod.js`
6. Repeat steps 4 + 5

After that you can use image plugin again w/o errors.

### PR DESCRIPTION
**Pull request by martinstuecklschwaiger**
I think this should fix ahmadawais/create-guten-block#124.

- `window.lodash` is already present in Gutenberg. 
- `window._` is underscore (not lodash, they differ only in some small details, but sometimes these do matter).
- If you import `lodash` in the code, it will override `window._` with lodash, which will cause weird bugs in totally unrelated places. This happens if you import some of the `@wordpress` Gutenberg modules.

Adding lodash here will prevent webpack from including `lodash` in the output, so it won't cause any conflicts. 

### How to test this
ahmadawais/create-guten-block#124 only happend on my system, if I installed some other plugins. The easiest way to reproduce it, is to install the `TinyMCE Advanced` plugin. 

In your block code: 
Add `import { compose } from "@wordpress/compose";` to one of the JavaScript files.

`@wordpress/compose` exports `flowRight` from `lodash` as `compose`, so it imports `lodash`. 
This will cause lodash to be included in your build. 

I created a minimal repository to show this: https://github.com/martinstuecklschwaiger/gutenberg-example

### CODE REVIEW

File: packages/cgb-scripts/config/externals.js [hunk 1]
```diff
@@ -41,6 +41,7 @@ const externals = [
 		react: 'React', // React itself is there in Gutenberg.
 		jquery: 'jQuery', // import $ from 'jquery' // Use the WordPress version after enqueuing it.
 		'react-dom': 'ReactDOM',
+		lodash: 'lodash', // Lodash is there in Gutenberg
```
Comment (ahmadawais) [inline packages/cgb-scripts/config/externals.js]: Missing period at the end of comment.

**Comment by ahmadawais** [comment]
Thanks just pushed an update.
